/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dnn_constants.h"

namespace dnn {

const dnnConstants g_dnn_constants;

dnnConstants::dnnConstants() {
}

} // namespace

