/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dnn_CONSTANTS_H
#define dnn_CONSTANTS_H

#include "dnn_types.h"

namespace dnn {

class dnnConstants {
 public:
  dnnConstants();

};

extern const dnnConstants g_dnn_constants;

} // namespace

#endif
