## Set Caffe path
# (be sure to run make distribute as the final step in Caffe)
CAFFE=/home/jahausw/projects/sirius-caffe/distribute

# Cuda path
CUDA=/usr/local/cuda

# CPU-only switch (uncomment to build without GPU support)
# Caffe must be built
CPU_ONLY := 1
