# DjiNN and Tonic Makefile.config
# Set Caffe path
# (be sure to run make distribute as the final step in Caffe)
CAFFE=/home/jahausw/projects/caffe/distribute

# Cuda path
CUDA=/usr/local/cuda

# CPU-only switch (uncomment to build without GPU support)
# Caffe must be built
# CPU_ONLY := 1

# Whatever else
INCLUDE_DIRS := -I/usr/local/include
LIBRARY_DIRS := -L/usr/local/lib
