/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dnn_constants.h"

namespace dnn { namespace cpp2 {

const dnnConstants g_dnn_constants;

}} // dnn::cpp2