/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dnn_types.h"

#include "dnn_types.tcc"

#include <algorithm>

namespace dnn { namespace cpp2 {

template uint32_t Work::read<apache::thrift::BinaryProtocolReader>(apache::thrift::BinaryProtocolReader*);
template uint32_t Work::write<apache::thrift::BinaryProtocolWriter>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Work::serializedSize<apache::thrift::BinaryProtocolWriter>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Work::serializedSizeZC<apache::thrift::BinaryProtocolWriter>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Work::read<apache::thrift::CompactProtocolReader>(apache::thrift::CompactProtocolReader*);
template uint32_t Work::write<apache::thrift::CompactProtocolWriter>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Work::serializedSize<apache::thrift::CompactProtocolWriter>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Work::serializedSizeZC<apache::thrift::CompactProtocolWriter>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Work::write<apache::thrift::DebugProtocolWriter>(apache::thrift::DebugProtocolWriter*) const;
template uint32_t Work::read<apache::thrift::VirtualReaderBase>(apache::thrift::VirtualReaderBase*);

void Work::__clear() {
  data.clear();
  op = std::string();
  n_in = 0;
  c_in = 0;
  w_in = 0;
  h_in = 0;
  __isset.__clear();
}

bool Work::operator==(const Work& rhs) const {
  if (!((data == rhs.data))) {
    return false;
  }
  if (!((op == rhs.op))) {
    return false;
  }
  if (!((n_in == rhs.n_in))) {
    return false;
  }
  if (!((c_in == rhs.c_in))) {
    return false;
  }
  if (!((w_in == rhs.w_in))) {
    return false;
  }
  if (!((h_in == rhs.h_in))) {
    return false;
  }
  return true;
}

void swap(Work& a, Work& b) {
  using ::std::swap;
  swap(a.data, b.data);
  swap(a.op, b.op);
  swap(a.n_in, b.n_in);
  swap(a.c_in, b.c_in);
  swap(a.w_in, b.w_in);
  swap(a.h_in, b.h_in);
  swap(a.__isset, b.__isset);
}

}} // dnn::cpp2
namespace apache { namespace thrift {

}} // apache::thrift
namespace dnn { namespace cpp2 {

}} // dnn::cpp2