/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "dnn_types.h"
namespace facebook { namespace windtunnel { namespace treadmill { namespace services { namespace dnn {

class dnnConstants {
 public:
  dnnConstants() {}
};

extern const dnnConstants g_dnn_constants;

}}}}} // facebook::windtunnel::treadmill::services::dnn