/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "dnn_types.h"
namespace dnn { namespace cpp2 {

class dnnConstants {
 public:
  dnnConstants() {}
};

extern const dnnConstants g_dnn_constants;

}} // dnn::cpp2