/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dnn_constants.h"

namespace facebook { namespace windtunnel { namespace treadmill { namespace services { namespace dnn {

const dnnConstants g_dnn_constants;

}}}}} // facebook::windtunnel::treadmill::services::dnn